### ISSUE TITLE
Error when running on linux

### ISSUE THREAD

**Issue by kirill-gerasimenko-da** [unfor19/parzival#1]
Hi! 

I wanted to test out the project, went with installation instructions for Linux (I've got Ubuntu 20.04) and constantly getting the following error when trying to run `parzival`:

```
bash: /usr/local/bin/parzival: No such file or directory
```

The file is definitely there, all permissions, user and group are set correctly - I'm 100% sure. I even tried to download from releases page directly - same kind of error. 

@unfor19 what do you think it could be? 

Thanks!

**Comment by unfor19** [comment]
Hi @kirill-gerasimenko-da,
Check the [Dockerfile](https://github.com/unfor19/parzival/blob/master/Dockerfile) of this project.

The final stage of the Dockerfile is running on [Linux Alpine](https://hub.docker.com/_/alpine):

```dockerfile
FROM alpine:${ALPINE_VERSION} AS app
WORKDIR "/app/"
COPY --from=build "/app/parzival" ./
RUN addgroup -S "appgroup" && adduser -S "appuser" -G "appgroup" && \
    chown "appuser":"appgroup" "parzival" && \
    chmod +x "parzival"
USER "appuser"
ENTRYPOINT ["/app/parzival"]
```

You've mentioned that you're on Ubuntu 20.04, is that WSL2 or have you installed Ubuntu directly on your machine?

- If WSL2 - make sure to use the **linux_386** binary, [check the Releases page](https://github.com/unfor19/parzival/releases)
- If installed Ubuntu directly on host machine, download the **linux_amd64** binary (unless you're on arm, and then you should choose the **linux_arm64** binary

Feel free to share the code snipped that you were trying to execute and we'll see how it can be fixed

**Comment by unfor19** [comment]
@kirill-gerasimenko-da I'm closing this one for now, I'll re-open this ticket if there's more input
